# Generated by Django 5.1.1 on 2024-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
